# Generated by Django 4.0.2 on 2022-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_options_category_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Валюта')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Стоимость')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
